<%@ page contentType="text/html;charset=UTF-8" %>

<html>
  <head>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
  <meta name='layout' content='main'/>
  <title>${grailsApplication.config.projectID} admin</title>
  <parameter name="admin" value="selected"></parameter>
  
 <script>
  function demoData(sp){
  	if (sp == "badger"){
		$("#dir").val("M_meles");
		//$("#trans").val("trans.fa"); $("#trans_v").val("1.1"); $("#trans_d").val("UniGenes"); $("select[name='trans_c']").val("n");
		$("#genome").val("m_meles_genome.fa"); $("#genome_v").val("1.0"); $("#genome_d").val("The genome of M. meles has not yet been sequences, this is just an example data set."); $("select[name='genome_c']").val("n");
		$("#genes").val("m_meles.gff"); $("#genes_v").val("1.1"); $("#genes_d").val("A GFF3 file generated by some gene prediction software");
		$("#mrna_trans").val("m_meles.transcripts.fasta"); $("#mrna_trans_v").val("1.1"); $("#mrna_trans_d").val("A set of transcripts based on the predicted genes");
		$("#mrna_pep").val("m_meles.proteins.fasta"); $("#mrna_pep_v").val("1.1"); $("#mrna_pep_d").val("A set of proteins based on the predicted genes");
	}
  }
  </script>
  
  </head>

  <body>
<div class="bread"><g:link action="home">Admin</g:link> > <g:link action="home">Home</g:link> > <g:link action="editSpecies" params="${[Gid:genome.meta.id]}"><i>${genome.meta.genus} ${genome.meta.species}</i></g:link> > Edit genome </div>
  
<h1>Edit genome data:</h1>

<g:form action="editedGenome">

<table>
	<tr>
		<td width="45%"><b>Date (leave blank for today's date)</b><font color="red">*</font><br>
			<g:textField value="${genome.dateString}" name="genome_date" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
		</td>
		<td width="50%"><b>Version (a unique ID for the genome)</b><font color="red">*</font><br>
			<g:textField value="${genome.gversion}" name="genome_version" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
		</td>
	</tr>
</table>	
<p><b>URL of Gbrowse2 instance</b></p>
<g:textField value="${genome.gbrowse}" name="gbrowse" style="width: 98%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/><br><br>
<br>
<input class="mybuttons" type="button" value="Update genome data" onclick="submit()" >
</g:form>
<hr size = 5 color="green" width="100%" style="margin-top:10px"><br>

<h1>Edit / delete a file set:</h1>

<table>
<g:if test="${genome.files}">
	<g:each var="f" in="${genome.files}">
	   <tr><td>
	   <div class="inline">
	   		<g:form action= "editFile" params="[gid: genome.id]" >
	    		<a href="#" onclick="parentNode.submit()" title="Edit file"><img src="${resource(dir: 'images', file: 'edit-icon.png')}" width="15px"/></a>
	    	</g:form>  	
	    	<g:form action="deleteFile" params="[gid: genome.id]" >
	    		<a href="#" onclick="parentNode.submit()" title="Delete file"><img src="${resource(dir: 'images', file: 'delete-icon.png')}" width="15px"/></a>
	    	</g:form> 	
	    </div>
      		</td><td>File type ${f.file_type}:</td><td>${f.file_name}</td></tr>
   	   </g:each>
</g:if>
<g:else>
	There are no files for this genome
</g:else>
</table>

<hr size = 5 color="green" width="100%" style="margin-top:10px"><br>

<g:form action="addedFiles">

<br>
<div class="inline">
	<h1>Add a file set for the genome:</h1> Examples: 
	<a href = "javascript:void(0)" onclick="demoData('badger')">M. meles </a>
</div><br>

	<h2><b>Data files</b></h2>	
	<p><b>Location (directory within data folder)</b><font color="red">*</font></p>
	<g:textField name="dir" style="width: 98%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/><br>
	<table width=100%>
		<tr>
			<td width="40%"><b>Genome (FASTA file)</b><font color="red">*</font><br>
				<g:textField name="genome" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td width="10%"><b>Version</b><font color="red">*</font><br>
				<g:textField name="genome_v" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td><b>Coverage</b><br>
				<select name="genome_c">
					<option selected="selected" value="n">No</option>
					<option value="y">Yes</option>				
				</select>
			</td>
			<td><b>Description</b><font color="red">*</font><br>
				<g:textField name="genome_d" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
		</tr>
		<tr>
			<td width="40%"><b>Genes (GFF3 file)</b><font color="red">*</font><br>
				<g:textField name="genes" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td width="10%"><b>Version</b><font color="red">*</font><br>
				<g:textField name="genes_v" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td colspan=2><b>Description</b><font color="red">*</font><br>
				<g:textField name="genes_d" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
		</tr>
		<tr>
			<td width="40%"><b>mRNA transcripts (FASTA file)</b><font color="red">*</font><br>
				<g:textField name="mrna_trans" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td width="10%"><b>Version</b><font color="red">*</font><br>
				<g:textField name="mrna_trans_v" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td colspan=2><b>Description</b><font color="red">*</font><br>
				<g:textField name="mrna_trans_d" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
		</tr>
		<tr>
			<td width="40%"><b>Peptide sequences (FASTA file)</b><font color="red">*</font><br>
				<g:textField name="mrna_pep" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td width="10%"><b>Version</b><font color="red">*</font><br>
				<g:textField name="mrna_pep_v" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
			<td colspan=2><b>Description</b><font color="red">*</font><br>
				<g:textField name="mrna_pep_d" style="width:100%; height: 18px; border: 3px solid #cccccc; padding: 2px;"/>
			</td>
		</tr>
	</table>
	<hr size = 5 color="green" width="100%" style="margin-top:10px"><br>
	
	<h2><b>Privacy</b></h2>	
	<table>
	<tr><td></td><td><b>Search</b></td><td><b>BLAST</b></td><td><b>Download</b></td></tr>
	<tr><td><b>Transcriptome</b></td>
	<td><select name="search_trans">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td>	
	<td><select name="blast_trans">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td>	
	<td><select name="down_trans">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td></tr>	
	
	<tr><td><b>Genome</b></td>
	<td><select name="search_genome">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td>	
	<td><select name="blast_genome">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td>	
	<td><select name="down_genome">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td></tr>	
	
	<tr><td><b>Genes</b></td>
	<td><select name="search_genes">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td>	
	<td></td>	
	<td><select name="down_genes">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td></tr>	
	
	<tr><td><b>mRNA</b></td>
	<td></td>
	<td><select name="blast_mrna">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td>	
	<td><select name="down_mrna">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td></tr>	
	
	<tr><td><b>Peptide</b></td>
		<td></td>
	<td><select name="blast_pep">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td>
	<td><select name="down_pep">
		<option value="pub">Public</option>
		<option value="priv">Private</option>
	</select></td></tr>	
	</table>
	<input type="hidden" name="gid" value="${genome.id}">
	<input class="mybuttons" type="button" value="Add new file set" onclick="submit()" >
	<hr size = 5 color="green" width="100%" style="margin-top:10px"><br>
	
</g:form>


</body>
</html>
